import Navbar from '@/components/Navbar';
import './globals.css';
import type { Metadata } from 'next';
import { Open_Sans } from 'next/font/google';
import Footer from '@/components/Footer';

const openSans = Open_Sans({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en' className={openSans.className}>
      <body className='w-full mx-auto'>
        <header className='sticky top-0 z-10 border-b'>
          <Navbar />
        </header>
        <main className='flex justify-center w-full max-w-screen-xl mx-auto grow pt-28'>
          {children}
        </main>
        {/* <Footer /> */}
      </body>
    </html>
  );
}
